# Generated by Django 3.2.7 on 2021-09-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('src', models.ImageField(upload_to='images/')),
                ('mode', models.CharField(choices=[('WB', 'Черные vs Белые'), ('HEX', 'Цвет по HEX-коду')], default='WB', max_length=30)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
    ]
