# Generated by Django 3.2.7 on 2021-09-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic_app', '0003_auto_20210914_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='color',
            field=models.CharField(blank=True, max_length=6, verbose_name='Код цвета #'),
        ),
    ]
