# Generated by Django 3.2.7 on 2021-09-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic_app', '0004_alter_pictures_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='mode',
            field=models.CharField(choices=[('WB', 'Черные vs Белые'), ('HEX', 'Цвет по HEX-коду')], default='HEX', max_length=30, verbose_name='Режим'),
        ),
    ]
